x-dev-base: &dev-base
  build:
    context: .
    dockerfile: .devcontainer/Dockerfile
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}

  volumes:
    - .:/workspace
  networks:
      - golang-dev-network
  working_dir: /workspace

services:

  dev:
    <<: *dev-base
    container_name: api_order_service

    command:
      - sleep
      - infinity

  dev-ssh:
    <<: *dev-base
    container_name: api_order_service_ssh

    ports:
      - "2222:22"
      - "8080:8080"

    command:
      - /usr/sbin/sshd
      - -D

  postgres:
    image: postgres:18
    container_name: db_order_service

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    networks:
      - golang-dev-network

volumes:
  postgres_data:
    name: order_service_postgres_data

networks:
  golang-dev-network:
    name: golang-dev-network
    driver: bridge
